/** Re-export shared cross-app URL helpers from @nertura/utils. */
export {
  ADMIN_DEV_PORT,
  DASHBOARD_DEV_PORT,
  MARKETING_DEV_PORT,
  buildDashboardUrl,
  coerceDashboardAuthUrl,
  containsLocalhostLeak,
  dashboardAppUrl,
  dashboardContextFromHeaders,
  dashboardContextFromRequest,
  getAppBaseUrl,
  getAuthCallbackUrl,
  getBrowserDashboardContext,
  getDashboardBaseUrl,
  getDashboardDoctorUrl,
  getDashboardLoginUrl,
  getDashboardRegisterUrl,
  isAllowedDevHostname,
  isLocalHostname,
  isPrivateLanHostname,
  isProductionNerturaHostname,
  sanitizeInternalPath,
  type DashboardUrlContext,
  type DashboardUrlParams,
} from '@nertura/utils';
