export const LEAD_DISCOVERY_CATEGORIES = [
  { id: 'university', label: 'Universities', sector: 'tarım fakültesi üniversite' },
  { id: 'ag_faculty', label: 'Agriculture Faculties', sector: 'ziraat fakültesi' },
  { id: 'gov_ag', label: 'Government Agriculture Offices', sector: 'tarım il müdürlüğü' },
  { id: 'farmer_assoc', label: 'Farmer Associations', sector: 'çiftçi birliği kooperatif' },
  { id: 'cooperative', label: 'Cooperatives', sector: 'tarım kooperatifi' },
  { id: 'greenhouse', label: 'Greenhouses', sector: 'sera işletmesi' },
  { id: 'ag_company', label: 'Agriculture Companies', sector: 'tarım şirketi' },
  { id: 'large_farm', label: 'Large Farms', sector: 'büyük çiftlik tarla' },
  { id: 'influencer', label: 'Agriculture Influencers', sector: 'tarım influencer' },
  { id: 'youtube', label: 'YouTube Channels', sector: 'tarım youtube kanalı' },
  { id: 'tiktok', label: 'TikTok Creators', sector: 'tarım tiktok' },
  { id: 'instagram', label: 'Instagram Pages', sector: 'tarım instagram' },
  { id: 'facebook', label: 'Facebook Communities', sector: 'tarım facebook grubu' },
  { id: 'linkedin', label: 'LinkedIn Organizations', sector: 'agriculture linkedin company' },
  { id: 'reddit', label: 'Reddit Communities', sector: 'farming reddit community' },
  { id: 'discord', label: 'Discord Communities', sector: 'agriculture discord' },
  { id: 'blog', label: 'Agriculture Blogs', sector: 'tarım blog' },
] as const;
